In [8]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# بارگیری دیتاست Iris
iris = load_iris()
X = iris.data  # ویژگی‌ها
y = iris.target  # برچسب‌ها

# چاپ شکل داده‌ها (اختیاری)
print("شکل داده‌های X:", X.shape)
print("شکل داده‌های y:", y.shape)

# تقسیم داده به داده‌های آموزشی و تست
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# ایجاد مدل KNN با K=3
knn = KNeighborsClassifier(n_neighbors=3)

# آموزش مدل
knn.fit(X_train, y_train)

# انتخاب یک نمونه از داده‌های تست (مثلاً اولین نمونه)
sample = X_test[0].reshape(1, -1)

# پیدا کردن نزدیک‌ترین همسایه‌ها
distances, indices = knn.kneighbors(sample)

# ذخیره داده‌های نزدیک‌ترین همسایه‌ها در یک لیست
nearest_neighbors = [X_train[i] for i in indices[0]]

print("نمونه داده جدید:")
print(sample)
print("\nنزدیک‌ترین همسایه‌ها:")
for neighbor in nearest_neighbors:
    print(neighbor)

شکل داده‌های X: (150, 4)
شکل داده‌های y: (150,)
نمونه داده جدید:
[[6.1 2.8 4.7 1.2]]

نزدیک‌ترین همسایه‌ها:
[6.1 2.9 4.7 1.4]
[6.1 3.  4.6 1.4]
[6.2 2.9 4.3 1.3]
